name: 'homeq'
version: '1.0.0'
profile: 'homeq'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  homeq:
    +schema: raw

models:
  homeq:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

